include(default)
[settings]
os=Emscripten
arch=wasm
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11
compiler.cppstd=20
[options]
[tool_requires]
[env]
CC=/usr/bin/gcc-13
CXX=/usr/bin/g++-13